Lesson2
Edjetics/GoCourse pull request #3
Opened 2021-07-11 22:24 UTC by Edjetics

2021-07-12 13:40 UTC, DzmitryYafremenka commented on lesson_02/output/output.go
> +func fibonacci(n int) (res int) {
This will do for homework. But this calculation algorithm is EXTREMELY inefficient. No need to fix now, but you can try to run it for say 100 numbers)

2021-07-12 13:40 UTC, DzmitryYafremenka commented on lesson_02/output/output.go
> +package output
Not a great choice of package name. This is quite important because all code is split into packages and the usability of the package will depend on the name chosen. The name of a package provides context for its contents, making it easier for consumers to understand what the package is for. "output" doesn't give me any information about what the package does. Outputs what? Current time? Date? The temperature? 
You can do better.)

2021-07-12 13:40 UTC, DzmitryYafremenka commented on lesson_02/output/output.go
> +func Result() {
Same. Function name should provide me information of its usage. "Result" is not what the function does. It **outputs** the result to the console. This is what I get as a consumer of this package. The Fibonacci sequence will appear in my console. So think about better naming.

2021-07-12 13:40 UTC, DzmitryYafremenka commented on lesson_02/output/output.go
> +	const number = 10
this should be a function argument. As described in HW - function should have a signature like
`func name(n int)` where n int is the amount of Fibonacci numbers to output

2021-07-12 17:09 UTC, DzmitryYafremenka approved these changes

2021-07-13 14:36 UTC, Edjetics commented on lesson_02/fibonacci/fibonacci.go
> +	x, y := 0, 1
Fixed

2021-07-14 07:04 UTC, IgorZhadenovEpam requested changes
Overall good. Need to be finalized. Please check my notes.

2021-07-14 19:56 UTC, Edjetics commented on lesson_02/hm002.go
> +func main() {
Added

2021-07-14 19:56 UTC, Edjetics commented on lesson_02/hm002.go
> +	fibonacci.OutputFib(number)
Fixed

2021-07-15 13:45 UTC, AliakseiM approved these changes

2021-07-19 07:14 UTC, closed without merging